spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
io:
  piratesking:
    uri: https://api.piratesking.io
    wallet-id: ${WALLET_ID}
    bot-id: ${BOT_ID}
    energy: ${ENERGY}
telegram:
  uri: https://api.telegram.org
  chat-id: ${CHAT_ID}
  token: ${TELEGRAM_TOKEN}